config/routes.rb
Rails.application.routes.draw do
 root "posts#index"

  post "/users/:user_id/posts/:post_id/comments/new" => "comments#create", as: :comments_create
  get "/users/:user_id/posts/:post_id/comments/" => "comments#new", as: :new_comment
  delete "/users/:user_id/posts/:id" => "posts#destroy", as: :delete_user_post
  resources :users do
    resources :posts do
      resources :comments 
    end
  end

  # delete "/users/:user_id/posts/:post_id/comments/:id" => "comments#destroy", as: :delete_user_post_comment

  # get "/users/:user_id/posts/:post_id/comments" => "comments#index"
  # get "/users/:user_id/posts/:post_id/comments/new" => "comments#new", as: :new_user_post_comment
  # get "/users/:user_id/posts/:post_id/comments/:id/edit" => "comments#edit", as: :edit_user_post_comment
  # get "/users/:user_id/posts/:post_id/comments/:id" => "comments#show", as: :user_post_comment 
  # patch "/users/:user_id/posts/:post_id/comments/:id" => "comments#update"
  # put "/users/:user_id/posts/:post_id/comments/:id" => "comments#update"


  # get "/users/:user_id/posts" => "posts#index", as: :user_posts
  # post "/users/:user_id/posts" => "posts#create"
  # get "/users/:user_id/posts/new" => "posts#new", as: :new_user_post
  # get "/users/:user_id/posts/:id/edit" => "posts#edit", as: :edit_user_post
  # get "/users/:user_id/posts/:id" => "posts#show", as: :user_post
  # patch "/users/:user_id/posts/:id" => "posts#update"
  # put "/users/:user_id/posts/:id" => "posts#update"
 

  # get "/users" => "users#index"
  # post "/users" => "users#create"
  # get "/users/new" => "users#new", as: :new_user
  # get "/users/:id/edit" => "users#edit", as: :edit_user 
  # get "/users/:id" => "users#show"
  # patch "/users/:id" => "users#update"
  # put "/users/:id" => "users#update"
  # delete "/users/:id" => "users#destroy"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	# has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
 #    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :posts
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def authenticate
    unless logged_in?
      flash[:error] = "You must be logged in to access this section of the site"
      redirect_to login_url
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	include SessionsHelper
	def index
		@comments = Comment.all 
		# @comment_count = @comment.count
	end

	def show
		@post = Post.find(params[:post_id])
		@comment = Comment.find(params[:id])
		@user = current_user
	end


	def new
    	@post = Post.find(params[:post_id])
    	@user = current_user
		@comment = Comment.new
		#@comment.user = current_user
	end

	def create
		@post = Post.find(params[:post_id])
		@comment = Comment.new( comment_params )
		#@post.comments.create(comment_params)
		#@comment.user = current_user
		@user = current_user
		@post.comments << @comment
		@user.comments << @comment
		if @comment.save
			redirect_to user_post_path(@user, @post)
		else
			render :new
		end
	end

	def edit
		@comment = Comment.find(params[:id])
	end

	def update	
		@comment = Comment.find(params[:id])
		if @comment.update
			redirect_to @comment, data: { alert: 'comment was successfully updated.' }
		else 
			render :edit
		end
	end

	def count
	end

	def destroy
		@comment = @Comment.find(params[:id])
    	@comment.destroy
			redirect_to user_posts_path, alert: "comment was successfully deleted."
	end

	private
	def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	include SessionsHelper
	def index
		@posts = current_user.posts
		if current_user.admin
			@posts = Post.all
		else
			@posts = current_user.posts
		end
		@user = current_user
	end

	def new
		@post = Post.new
		@user = current_user
	end

	def create
		@user = User.find(current_user)
		@post = @user.posts.new(post_params)
   		if @post.save
    		redirect_to user_posts_path
    	else
    		render :new
    	end
	end

	def show
		@user = User.find( current_user[:id])
		@post = Post.find(params[:id])
	end

	def edit
		@user = current_user
		@post = Post.find(params[:id])
		# cannot delete edited message
		
	end

	def update
		@post = Post.find(params[:id])
		@user = current_user
		if @post.update_attributes(post_params)
			# why attributes
			redirect_to user_posts_path, notice: 'Post was successfully updated.'
		else 
			render :edit
		end
	end

	def destroy
	   post = Post.find(params[:id])
	   Comment.where({post_id: post.id }).destroy_all
	   Post.destroy( post.id )
	   redirect_to user_posts_path
	end

	private
	def post_params
      params.require(:post).permit(:title, :content, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	include SessionsHelper
	def new
	end
	
	def create
		user = User.find_by(email: params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id.to_s
	     	redirect_to root_path
     	else
     		render :new
     	end
	end
	
	def destroy
		session.delete(:user_id)
	    redirect_to login_path
	end

	private

  	def session_params
    	params.require(:user).permit(:email, :password)
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  def index
    @users = User.all
  end

  def show
    @user =User.find(params[:id])
    @posts = Post.where({user_id: @user.id})
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
	  current_user ||= User.find_by(id: session[:user_id])
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<section class="newPostForm">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
		<div class="col-sm-12 col-sm-offset-1">

		<%= form_for :comment, url: user_post_comment_path(@comment.user_id, @comment.id, @comment.post_id), method: :comment do |f| %>
		    <div>
		    <ul>
		      <li><%= f.label :body %></li>
		      <li><%= f.text_field :body %></li>
		     </ul>
		    </div>

		    <div>
		      <%= f.submit %>
		
		  <div><%= link_to 'Show', user_post_path(@comment.id, @comment.post_id) %></div>
			<% end %>
		    </div>
		  </div>
      </div>
    </div>
  </div>
</section>

app/views/comments/index.html.erb
<h1>My comments page</h1>
 
<h2>Add a comment:</h2>
	<%= form_for @comment do |f| %>
  		<ul>
		    <li><%= f.label :body %></li>>
		    <li><%= f.text_area :body %></li>
  		</ul>
  		<p>
    		<%= f.submit %>
  		</p>
	<% end %>


	<%= link_to 'Back', user_posts_path %>
	<% if current_user && current_user.admin == true %>
	<%= link_to 'edit comment', edit_user_post_comment_path %>
	<% end %>

app/views/comments/new.html.erb
<section class="newComment">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
		<div class="col-sm-12 col-sm-offset-1">
			<%= form_for :comment do|f| %>
		    	<div>	
		    	<ul>
			    	<li><%= f.label :body %></li>
			     	<li><%= f.text_field :body, class: "form-control" %></li>
			    </ul>
			    </div>
		    <div class="pushDown30"></div>
		     	<%= f.submit %>
		      	<% end %>
		  		</div>
			<div class="col-sm-10 col-sm-offset-1">
			<div class="pushDown30"><%= link_to 'Show Posts', user_posts_path( current_user.id ) %></div>
      </div>
    </div>
  </div>
</section>

app/views/comments/show.html.erb
<section class="postShow">
  <div class="container">
    <div ="row">
      <div class="col-sm-12">

      <h1>This is a comment!</h1>
        <p>
          <strong>Title:</strong>
          <%= @post.title %>
        </p>
        <ul>
          <strong>Content:</strong>
          <li><%= @post.content %></li>
        </ul>
        </br>
        <h2>Add a comment:</h2>
          <%= form_for([post_id, @post.comments.new]) do |f| %>
          <ul>
            <li><%= f.label :body %></li>
            <li><%= f.text_area :body %></li>
          </ul>
          <p>
            <%= f.submit %>
          </p>
          <% end %>

        <%= link_to 'Edit', edit_user_post_path(@user, @post) %> 
        <%= link_to 'Back', user_posts_path %>

        </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DogoodBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<%= render "partials/navbar" %>

<%= yield %>

</body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       
		<% if current_user %>
		  <li><%= link_to current_user.name , users_path %></li>
		    
		 <li><%= link_to "Log Out", logout_path, method: :delete, class: "glyphicon glyphicon-log-out" %></li>

		<% else %>
		    <li><%= link_to "Log In", login_path %></li>
		    <li><%= link_to "Sign Up", new_user_path, class: "glyphicon glyphicon-user" %></li>
		<% end %>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
		      <li><%= link_to "Posts", root_path %></li>
		      <li><%= link_to "Profile", users_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Posts", user_posts_path(:user_id) %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_showposts.html.erb
	<ul>
	<% @posts.each do |post| %>
		<li><%= post.title %></li>
		<li><%= post.content %></li>
	<% end %>
	</ul>

app/views/posts/edit.html.erb
<section>
  <div class="container">
    <div ="row">
      <div class="col-sm-12 text-center">
        <h1>Editing post</h1>
        <div>
        <%= form_for [@user, @post] do |f| %>
            <ul>
              <li><%= f.label :title %></li>
              <li><%= f.text_field :title %></li>
            </ul>
            <ul>
              <li><%= f.label :content %></li>
              <li><%= f.text_field :content, class: "paddedInput" %></li>
            </ul>

            <ul>
              <li><%= f.submit %></li>

            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/index.html.erb
<section>
  <div class="container">
    <div ="row">
      <div class="col-sm-12">
      <h1>My Blog Posts!</h1>
        <% if current_user != nil %>
        <ul class="pushDown30">
        <li><%= link_to 'New Post', new_user_post_path(@user) %></li>
        </ul>
        <% end %>
        <% @posts.each do |post| %>
          <ul>
            <strong>Post Title:</strong>
            <li><%= post.title %></li>
            <strong>Post Content:</strong>
            <li><%= post.content %></li>
          </ul>
          <ul>
            <li><%= link_to 'show comments', user_post_path(@user.id, post) %></li>
            <% if current_user.id == post.user_id || current_user.admin == true %>
              <li><%= link_to 'Post', edit_user_post_path(@user.id, post), class: "glyphicon glyphicon-pencil" %></li>
              <li><%= link_to 'Post', delete_user_post_path(@user.id, post), method: :delete, class: "glyphicon glyphicon-trash" %></li>
              <li><%= link_to 'Add comment', user_post_comments_path(@user.id, post), class: "glyphicon glyphicon-comment" %></li>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/new.html.erb
<section class="newPostForm">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1>Upload a post</h1>

        <%= form_for :post, url: user_posts_path(@user), method: :post do |f| %>
          <div>
            <ul>
              <li><%= f.label :title %><li>
              <li><%= f.text_field :title %></li>
            </ul>
             <ul>
                <li><%= f.label :content %></li>
                <li><%= f.text_field :content, class: "form-control" %></li>
            </ul>
            <div class="pushDown30">
              <%= f.submit %>
            </div>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<section class="postShow">
  <div class="container">
    <div ="row">
      <div class="col-sm-12">
		<h1 class="headerFormat">My Daily Gratitiude!</h1>
		<h2>Write your thanks</h2>
		<ul>
			<strong>Post Title:</strong>
			<li><%= @post.title %></li>
			<strong>Post Content:</strong>
			<li><%= @post.content %></li>
		</ul>
		<ul>
			<% @post.comments.each do |comment| %>
				<strong> Comments:</strong>
				<li><%= comment.body %></li>
					<% if current_user.id == comment.user_id || current_user.admin == true %>
					<%= link_to 'edit comment', edit_user_post_comment_path(comment.user_id, @post.id, comment.id) %>
					<% end %>
			<% end %>
		</ul>


		<%= link_to 'Edit', edit_user_post_path(@user, @post) %>|
		<%= link_to 'Back', user_posts_path %>|
		<%= link_to 'Add comment', new_comment_path(@user.id, @post) %>

      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="postShow">
  <div class="container">
    <div ="row">
      <div class="col-sm-12">

		<h1>Users</h1>
		<ul>
		  <% @users.each do |user| %>
		    <li><%= user.name %></li>

		        <h5>Posts</h5>
		    	<ul>
				<% user.posts.each do |p| %>
					<li><%= p.title %></li>
					<li><%= p.content %></li>
				<% end %>
		</ul>
			<% end %>
		</ul>
      </div>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<section class="newUser">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 text-center">
        <h1>Signup and DOGOOD</h1>
        <%= form_for @user do |f| %>
          <ul>
            <li><%= f.label :name %></li>
            <li><%= f.text_field :name %></li>
          </ul>
          
          <ul>
            <li><%= f.label :email %></li>
            <li><%= f.text_field :email %></li>
          </ul>

          <ul>
            <li><%= f.label :password %></li>
            <li><%= f.password_field :password %></li>
          </ul>

          <ul>
            <li><%= f.label :password_confirmation %></li>
            <li><%= f.password_field :password_confirmation %></li>
          </ul>

          <ul class="pushDown30">
            <li><%= f.submit %></li>
          </ul>
        <% end %>
      </div>
      <div class="col-sm-6">
        <img src="http://www.braintreepayments.com/blog/content/images/2015/06/do-good.jpg" class="img-responsive">
      </div>
    </div><!-- row -->
  </div><!-- container -->
</section>

app/views/users/show.html.erb
<h1>Welcome new user!</h1>
	<p>
	<strong>Title:</strong>
	<ul>
	<% @posts.each do |post| %>
		<li><%= post.title %></li>
		<li><%= post.content %></li>
	<% end %>
	</ul>

  	<%= link_to "create new", new_user_post_path(@user, @post) %>
	</p>